//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebraEventManagement.AdminServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceRef.AdminServiceSoap")]
    public interface AdminServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateAdmin", ReplyAction="*")]
        DebraEventManagement.AdminServiceRef.ValidateAdminResponse ValidateAdmin(DebraEventManagement.AdminServiceRef.ValidateAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.ValidateAdminResponse> ValidateAdminAsync(DebraEventManagement.AdminServiceRef.ValidateAdminRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateAdmin", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.AdminServiceRef.ValidateAdminRequestBody Body;
        
        public ValidateAdminRequest() {
        }
        
        public ValidateAdminRequest(DebraEventManagement.AdminServiceRef.ValidateAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateAdminRequestBody() {
        }
        
        public ValidateAdminRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public DebraEventManagement.AdminServiceRef.ValidateAdminResponseBody Body;
        
        public ValidateAdminResponse() {
        }
        
        public ValidateAdminResponse(DebraEventManagement.AdminServiceRef.ValidateAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateAdminResult;
        
        public ValidateAdminResponseBody() {
        }
        
        public ValidateAdminResponseBody(bool ValidateAdminResult) {
            this.ValidateAdminResult = ValidateAdminResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceSoapChannel : DebraEventManagement.AdminServiceRef.AdminServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceSoapClient : System.ServiceModel.ClientBase<DebraEventManagement.AdminServiceRef.AdminServiceSoap>, DebraEventManagement.AdminServiceRef.AdminServiceSoap {
        
        public AdminServiceSoapClient() {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DebraEventManagement.AdminServiceRef.ValidateAdminResponse DebraEventManagement.AdminServiceRef.AdminServiceSoap.ValidateAdmin(DebraEventManagement.AdminServiceRef.ValidateAdminRequest request) {
            return base.Channel.ValidateAdmin(request);
        }
        
        public bool ValidateAdmin(string username, string password) {
            DebraEventManagement.AdminServiceRef.ValidateAdminRequest inValue = new DebraEventManagement.AdminServiceRef.ValidateAdminRequest();
            inValue.Body = new DebraEventManagement.AdminServiceRef.ValidateAdminRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            DebraEventManagement.AdminServiceRef.ValidateAdminResponse retVal = ((DebraEventManagement.AdminServiceRef.AdminServiceSoap)(this)).ValidateAdmin(inValue);
            return retVal.Body.ValidateAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.ValidateAdminResponse> DebraEventManagement.AdminServiceRef.AdminServiceSoap.ValidateAdminAsync(DebraEventManagement.AdminServiceRef.ValidateAdminRequest request) {
            return base.Channel.ValidateAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebraEventManagement.AdminServiceRef.ValidateAdminResponse> ValidateAdminAsync(string username, string password) {
            DebraEventManagement.AdminServiceRef.ValidateAdminRequest inValue = new DebraEventManagement.AdminServiceRef.ValidateAdminRequest();
            inValue.Body = new DebraEventManagement.AdminServiceRef.ValidateAdminRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((DebraEventManagement.AdminServiceRef.AdminServiceSoap)(this)).ValidateAdminAsync(inValue);
        }
    }
}
